codecov:
  branch: master

coverage:
  precision: 2
  round: up

  ignore:
      - "test/com/transgressoft/musicott/tests/JavaFxTestBase.java"
      - "src/com/google/common/graph/ConfigurableMutableGraph.java"
      - "src/com/google/common/graph/ConfigurableMutableValueGraph.java"
      - "src/com/google/common/graph/ElementOrder.java"
